export const AUTH_ERROR_CODES = Object.freeze({
    INVALID_EMAIL_VERIFICATION_TOKEN: "INVALID_EMAIL_VERIFICATION_TOKEN",
    EXPIRED_EMAIL_VERIFICATION_TOKEN: "EXPIRED_EMAIL_VERIFICATION_TOKEN",
    EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
    VALIDATION_ERROR: "VALIDATION_ERROR",
});

export const PENDING_VERIFICATION_EMAIL_KEY = "terangalink.pendingVerificationEmail";
